import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // ── Stitch exact tokens ───────────────────────────────
        "surface":                  "#131315",
        "surface-dim":              "#131315",
        "surface-bright":           "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low":    "#1b1b1d",
        "surface-container":        "#1f1f21",
        "surface-container-high":   "#2a2a2c",
        "surface-container-highest":"#353437",
        "on-surface":               "#e4e2e4",
        "on-surface-variant":       "#c1c6d7",
        "inverse-surface":          "#e4e2e4",
        "inverse-on-surface":       "#303032",
        "outline":                  "#8b90a0",
        "outline-variant":          "#414755",
        "surface-tint":             "#adc6ff",
        "primary":                  "#adc6ff",
        "on-primary":               "#002e69",
        "primary-container":        "#4b8eff",
        "on-primary-container":     "#00285c",
        "inverse-primary":          "#005bc1",
        "secondary":                "#c2c1ff",
        "on-secondary":             "#1c0b9f",
        "secondary-container":      "#3834b6",
        "on-secondary-container":   "#b2b1ff",
        "tertiary":                 "#47e266",
        "on-tertiary":              "#003910",
        "tertiary-container":       "#00a73e",
        "on-tertiary-container":    "#00320d",
        "error":                    "#ffb4ab",
        "on-error":                 "#690005",
        "error-container":          "#93000a",
        "on-error-container":       "#ffdad6",
        "background":               "#131315",
        "on-background":            "#e4e2e4",
        "surface-variant":          "#353437",
      },
      fontFamily: {
        "display":           ["Inter", "sans-serif"],
        "headline-lg":       ["Inter", "sans-serif"],
        "headline-lg-mobile":["Inter", "sans-serif"],
        "headline-md":       ["Inter", "sans-serif"],
        "body-lg":           ["Inter", "sans-serif"],
        "body-md":           ["Inter", "sans-serif"],
        "label-md":          ["Inter", "sans-serif"],
        "label-sm":          ["Inter", "sans-serif"],
      },
      fontSize: {
        "display":            ["48px", { lineHeight: "56px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg":        ["32px", { lineHeight: "40px",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md":        ["20px", { lineHeight: "28px",  fontWeight: "600" }],
        "body-lg":            ["18px", { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":            ["16px", { lineHeight: "24px",  fontWeight: "400" }],
        "label-md":           ["14px", { lineHeight: "20px",  letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm":           ["12px", { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        "sm":  "0.25rem",
        "DEFAULT": "0.5rem",
        "md":  "0.75rem",
        "lg":  "1rem",
        "xl":  "1.5rem",
        "full":"9999px",
      },
      spacing: {
        "xs":     "4px",
        "sm":     "12px",
        "base":   "8px",
        "md":     "24px",
        "lg":     "48px",
        "xl":     "80px",
        "gutter": "24px",
        "margin": "32px",
      },
      maxWidth: {
        "app": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
